/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pbi_dvb_domain_ConfigBean */

#ifndef _Included_com_pbi_dvb_domain_ConfigBean
#define _Included_com_pbi_dvb_domain_ConfigBean
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pbi_dvb_domain_ConfigBean
 * Method:    getParams
 * Signature: (Lcom/pbi/dvb/domain/ConfigBean;)V
 */
JNIEXPORT void JNICALL Java_com_pbi_dvb_domain_ConfigBean_getParams
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_pbi_dvb_domain_ConfigBean
 * Method:    setParams
 * Signature: (Lcom/pbi/dvb/domain/ConfigBean;)V
 */
JNIEXPORT void JNICALL Java_com_pbi_dvb_domain_ConfigBean_setParams
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
