/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pbi_dvb_dvbinterface_NativeCA */

#ifndef _Included_com_pbi_dvb_dvbinterface_NativeCA
#define _Included_com_pbi_dvb_dvbinterface_NativeCA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pbi_dvb_dvbinterface_NativeCA
 * Method:    setNormalSN
 * Signature: (Ljava/lang/String;)V
 */
 JNIEXPORT jint  JNICALL Java_com_pbi_dvb_dvbinterface_NativeCA_SendMessageToCA
	(JNIEnv *env, jobject obj, jint type,jobject objData, jint arg1);

JNIEXPORT jint	JNICALL Java_com_pbi_dvb_dvbinterface_NativeCA_GetCaData
	(JNIEnv *env, jobject obj, jobject objData);

JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativeCA_GetIPPRecord
	(JNIEnv *env, jobject obj, jobject objData);

JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativeCA_GetIPPProduct
	(JNIEnv *env, jobject obj, jobject objData);

JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativeCA_GetEntitle
	(JNIEnv *env, jobject obj, jobject objdata);

JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativeCA_GetEpuse
	(JNIEnv *env, jobject obj, jobject data);

JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativeCA_SetRating
(JNIEnv *env, jobject obj,jstring jsPin,jint llen ,jint lLevel);


JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativeCA_ChangePin
(JNIEnv *env, jobject obj, jstring jsOldPin, jstring jsNewPin,jint pinlen);


JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativeCA_caParentalCtrlUnlock
	(JNIEnv *env, jobject obj,jstring jsPin,jint plen );


/*获取智能卡状态,0:卡插入，1;卡拔出，2:卡错误；3:未知卡-1,取卡状态错误*/
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativeCA_CaGetScStatus
(JNIEnv *env, jobject obj);


JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativeCA_GetEntitleByPage
(JNIEnv *env, jobject obj, jobject objdata,int pagenum,int getnumber);

JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativeCA_GetEntitleTotals
(JNIEnv *env, jobject obj);


/*获取当前的智能卡状态0:成功；-1:未知智能卡，-2:请插入智能卡*/
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativeCA_factoryResetTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

