/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pbi_dvb_dvbinterface_NativeDrive */

#ifndef _Included_com_pbi_dvb_dvbinterface_NativeDrive
#define _Included_com_pbi_dvb_dvbinterface_NativeDrive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pbi_dvb_dvbinterface_NativeDrive
 * Method:    pvwareDRVInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativeDrive_pvwareDRVInit
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativeDrive_CAInit
  (JNIEnv *, jobject);
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativeDrive_DrvPlayerInit
  (JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativeDrive_DrvPlayerUnInit
  (JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativeDrive_DrvPmocSetWakeUp
  (JNIEnv *env, jobject obj, jobject WakeUpObj);
/*
JNIEXPORT void JNICALL Java_com_pbi_dvb_dvbinterface_NativeDrive_DrvFPClear
  (JNIEnv *env, jobject obj);
*/
#ifdef __cplusplus
}
#endif
#endif

