/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pbi_dvb_dvbinterface_NativePlayer */

#ifndef _Included_com_pbi_dvb_dvbinterface_NativePlayer
#define _Included_com_pbi_dvb_dvbinterface_NativePlayer

#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_TestStop
  (JNIEnv *env, jobject obj);

JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_TestPlay1
  (JNIEnv *env, jobject obj);

JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_TestPlay2
  (JNIEnv *env, jobject obj);

/*
 * Class:     com_pbi_dvb_dvbinterface_NativePlayer
 * Method:    DVBPlayer_Init
 * Signature: (Lcom/pbi/dvb/dvbinterface/NativePlayer/DVBPlayer_Config_t;)I
 */
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerInit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_pbi_dvb_dvbinterface_NativePlayer
 * Method:    DVBPlayer_Deinit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerDeinit
  (JNIEnv *, jobject);

/*
 * Class:     com_pbi_dvb_dvbinterface_NativePlayer
 * Method:    DVBPlayer_Set_Attr
 * Signature: (Lcom/pbi/dvb/dvbinterface/NativePlayer/DRV_AVCtrl_VidWindow_t;)I
 */
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerAVCtrlSetWindows
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_pbi_dvb_dvbinterface_NativePlayer
 * Method:    DVBPlayer_Get_Attr
 * Signature: (Lcom/pbi/dvb/dvbinterface/NativePlayer/DRV_AVCtrl_VidWindow_t;)I
 */
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerAVCtrlGetWindows
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_pbi_dvb_dvbinterface_NativePlayer
 * Method:    DVBPlayer_Play_Program
 * Signature: (Lcom/pbi/dvb/dvbinterface/NativePlayer/DVBPlayer_Play_Param_t;)I
 */
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerPlayProgram
  (JNIEnv *, jobject, jobject);


JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerSetStopMode
  (JNIEnv *env, jobject obj, jint mode);
/*
 * Class:     com_pbi_dvb_dvbinterface_NativePlayer
 * Method:    DVBPlayer_Stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerStop
  (JNIEnv *, jobject);

/*
 * Class:     com_pbi_dvb_dvbinterface_NativePlayer
 * Method:    DVBPlayer_Get_Info
 * Signature: (Lcom/pbi/dvb/dvbinterface/NativePlayer/DVBPlayer_Info_t;)I
 */
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerGetInfo
  (JNIEnv *, jobject, jobject );


JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerGetCaMode
  (JNIEnv *env, jobject obj );


JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerSwitchAudio
  (JNIEnv *env, jobject obj, jobject audioobj );
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerAVCtrlAudMute
  (JNIEnv *env, jobject obj, jint isMute );
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerAVCtrlSetVolume
  (JNIEnv *env, jobject obj, jint VoluemeFlag );
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerAVCtrlAudMode
  (JNIEnv *env, jobject obj, jint mode );
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerAVCtrlGetAudMode
  (JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerAVCtrlSetVPathPara
  (JNIEnv *env, jobject obj, jint dvb );


#if 0
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerPvrInit
  (JNIEnv *env, jobject obj );
#endif  
JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerPvrRecStart
  (JNIEnv *env, jobject obj, jobject PvrRecObj );

JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerPvrRecStop
  (JNIEnv *env, jobject obj );

JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerPvrRecGetStatus
  (JNIEnv *env, jobject obj, jobject RecStatusObj );

JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerPvrPlayStart
  (JNIEnv *env, jobject obj, jobject PvrPlayObj );

JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerPvrPlayStop
  (JNIEnv *env, jobject obj );

JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerPvrPlayPause
  (JNIEnv *env, jobject obj );

JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerPvrPlayResume
  (JNIEnv *env, jobject obj );

JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerPvrPlaySpeedCtrl
  (JNIEnv *env, jobject obj, jint Speed );

JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerPvrPlayGetFileInfo
  (JNIEnv *env, jobject obj, jobject FileInfo );

JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerPvrPlayGetStatus
  (JNIEnv *env, jobject obj, jobject PlayStauts );

JNIEXPORT jint JNICALL Java_com_pbi_dvb_dvbinterface_NativePlayer_DVBPlayerPvrRemoveFile
  (JNIEnv *env, jobject obj, jstring sFileName );

#ifdef __cplusplus
}
#endif
#endif
